ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    print_diagnostics: true
    permit_corrected_publication: true
    publish_tf: true

    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    two_d_mode: true

    # Optical Encoders
    odom0: "/diffbot_base_controller/odom"
    odom0_config: [true, true, false,
                   false, false, true,
                   true, true, true,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10
    odom0_nodelay: false
    odom0_differential: false
    odom0_relative: false
    odom0_pose_use_child_frame: false
    odom0_pose_rejection_threshold: 0.5  # Adjusted to 0.05 for pose rejection threshold
    odom0_twist_rejection_threshold: 0.5  # Adjusted to 0.05 for twist rejection threshold

    # RealSense D455 IMU - Linear Acceleration
    imu0: "/camera/realsense2_camera/accel/corrected"
    imu0_config: [false, false, false,  # Don't use orientation
                  false, false, false,  # Don't use angular velocity
                  false, false, false,  # Don't use linear velocity
                  false, false, false,  # Don't use orientation velocity
                  true,  true,  true]    # Use linear acceleration x, y, z
    imu0_differential: false
    imu0_queue_size: 5
    imu0_remove_gravitational_acceleration: false
    imu0_linear_acceleration_rejection_threshold: 0.2  # Adjusted to 0.02 for linear acceleration rejection threshold

    # RealSense D455 IMU - Angular Velocity
    imu1: "/camera/realsense2_camera/gyro/corrected"
    imu1_config: [false, false, false,   # Don't use orientation
                  true,  true,  true,    # Use angular velocity x, y, z
                  false, false, false,   # Don't use linear velocity
                  false, false, false,   # Don't use orientation velocity
                  false, false, false]   # Don't use linear acceleration
    imu1_queue_size: 5
    imu1_remove_gravitational_acceleration: false
    imu1_twist_rejection_threshold: 0.8  # Adjusted to 0.08 for twist rejection threshold
    imu1_angular_velocity_rejection_threshold: 0.3  # Adjusted to 0.03 for angular velocity rejection threshold

    # use_control: true
    # stamped_control: false



