ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    print_diagnostics: true
    permit_corrected_publication: true
    publish_tf: true

    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    two_d_mode: true

    # values are   x, y, z, 
    #             roll, pitch, yaw, 
    #             vx, vy, vz, 
    #             vroll, vpitch, vyaw, 
    #             ax, ay, az
    odom0: "/diffbot_base_controller/odom"
    odom0_config: [true, true, true,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,]
    odom1_pose_rejection_threshold: 2.0
    odom1_twist_rejection_threshold: 0.2

    imu1: "/camera/realsense2_camera/gyro/corrected"
    imu1_config: [false, false, false,  # Don't use orientation
                  true,  true,  true,  # Use angular velocity x, y, z
                  false, false, false,  # Don't use linear velocity
                  false, false, false,  # Don't use orientation velocity
                  false, false, false]  # Don't use linear acceleration
    imu1_remove_gravitational_acceleration: true
    imu1_angular_velocity_rejection_threshold: 0.05

    imu0: "/camera/realsense2_camera/accel/corrected"
    imu0_config: [false, false, false,  # Don't use orientation
                  false, false, false,  # Don't use angular velocity
                  false, false, false,  # Don't use linear velocity
                  false, false, false,  # Don't use orientation velocity
                  true,  true,  true]  # Use linear acceleration x, y, z,
    imu0_differential: false
    imu0_remove_gravitational_acceleration: false
    imu0_linear_acceleration_rejection_threshold: 0.8

