ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    print_diagnostics: true
    permit_corrected_publication: true
    publish_tf: true

    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    two_d_mode: true

    # values are   x, y, z, 
    #             roll, pitch, yaw, 
    #             vx, vy, vz, 
    #             vroll, vpitch, vyaw, 
    #             ax, ay, az
    pose0: "/diffbot_base_controller/odom"
    pose0_config: [true, true, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,]
    pose0_queue_size: 5
    pose0_rejection_threshold: 2.0

    twist0: "/diffbot_base_controller/odom"
    twist0_config: [false, false, false,
                   false, false, false,
                   true, true, true,
                   false, false, false,
                   false, false, false,]
    twist0_queue_size: 5
    twist0_rejection_threshold: 2.0

    imu0: "/camera/realsense2_camera/accel/corrected"
    imu0_config: [false, false, false,  # Don't use orientation
                  false, false, false,  # Don't use angular velocity
                  false, false, false,  # Don't use linear velocity
                  false, false, false,  # Don't use orientation velocity
                  true,  true,  true]  # Use linear acceleration x, y, z,
    imu0_differential: false
    imu0_queue_size: 5
    imu0_remove_gravitational_acceleration: false
    imu0_linear_acceleration_rejection_threshold: 0.8

    imu1: "/camera/realsense2_camera/gyro/corrected"
    imu1_config: [false, false, false,  # Don't use orientation
                  true,  true,  true,  # Use angular velocity x, y, z
                  false, false, false,  # Don't use linear velocity
                  false, false, false,  # Don't use orientation velocity
                  false, false, false]  # Don't use linear acceleration
    imu1_queue_size: 5
    imu1_remove_gravitational_acceleration: false
    imu1_twist_rejection_threshold: 0.8
    imu1_angular_velocity_rejection_threshold: 0.05

    use_control: true
    stamped_control: false



