ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    print_diagnostics: true
    permit_corrected_publication: true
    publish_tf: true

    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    odom0: "odom"
    odom0_config: [true, true, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    imu0: "/camera/realsense2_camera/gyro/corrected"
    imu0_config: [false, false, false,  # Don't use orientation
                  false,  false,  false,  # Use angular velocity x, y, z
                  false, false, false,  # Don't use linear velocity
                  false, false, false,  # Don't use orientation velocity
                  false, false, false]  # Don't use linear acceleration

    imu0_remove_gravitational_acceleration: false

    imu1: "/camera/realsense2_camera/accel/corrected"
    imu1_config: [false, false, false,  # Don't use orientation
                  false, false, false,  # Don't use angular velocity
                  false, false, false,  # Don't use linear velocity
                  false, false, false,  # Don't use orientation velocity
                  false,  false,  true]  # Use linear acceleration x, y, z,
    imu1_differential: false
    imu1_remove_gravitational_acceleration: false
    imu1_linear_acceleration_rejection_threshold: 0.8


