realsense2_camera:
  ros__parameters:
    camera_name: 'D455'
    serial_no: ''
    base_frame_id: 'camera_link'
    depth_module.profile: '1280x720x30'
    rgb_camera.profile: '1280x720x30'
    enable_depth: true
    enable_infra1: true
    enable_infra2: true
    enable_color: true
    align_depth: true
    depth_frame_id: 'camera_depth_frame'
    enable_pointcloud: true

    enable_accel: true
    enable_gyro: true
    unite_imu_method: "linear_interpolation"
    publish_tf: true
    tf_publish_rate: 30.0
    